-- mysuperdatabase — DB init SQL template
-- Generated by provision.sh via envsubst
-- Sets passwords for all Supabase service roles and reassigns ownership
-- of auth schema objects so GoTrue migrations can run.
-- Must be run as supabase_admin (superuser).

-- ─── Service role passwords ───────────────────────────────────────────────────
-- Plain ALTER ROLE is blocked on reserved roles; use DO+EXECUTE to bypass.
DO $$
BEGIN
  EXECUTE format('ALTER ROLE authenticator WITH PASSWORD %L', '${DB_PASSWORD}');
  EXECUTE format('ALTER ROLE supabase_auth_admin WITH PASSWORD %L', '${DB_PASSWORD}');
  EXECUTE format('ALTER ROLE supabase_storage_admin WITH PASSWORD %L', '${DB_PASSWORD}');
EXCEPTION WHEN OTHERS THEN
  RAISE WARNING 'Could not set role password: %', SQLERRM;
END;
$$;

-- ─── Auth schema ownership ───────────────────────────────────────────────────
-- supabase/postgres pre-creates auth.uid/role/email owned by postgres.
-- GoTrue migrations use CREATE OR REPLACE which requires ownership.
DO $$
BEGIN
  -- Transfer function ownership
  IF EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON p.pronamespace=n.oid WHERE n.nspname='auth' AND p.proname='uid') THEN
    EXECUTE 'ALTER FUNCTION auth.uid() OWNER TO supabase_auth_admin';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON p.pronamespace=n.oid WHERE n.nspname='auth' AND p.proname='role') THEN
    EXECUTE 'ALTER FUNCTION auth.role() OWNER TO supabase_auth_admin';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON p.pronamespace=n.oid WHERE n.nspname='auth' AND p.proname='email') THEN
    EXECUTE 'ALTER FUNCTION auth.email() OWNER TO supabase_auth_admin';
  END IF;
  -- Transfer any pre-existing auth tables
  PERFORM 1; -- no-op placeholder
EXCEPTION WHEN OTHERS THEN
  RAISE WARNING 'Auth schema ownership setup: %', SQLERRM;
END;
$$;

-- ─── Realtime schema ─────────────────────────────────────────────────────────
-- supabase/realtime expects _realtime schema to exist before running migrations
CREATE SCHEMA IF NOT EXISTS _realtime;
ALTER SCHEMA _realtime OWNER TO supabase_admin;
GRANT ALL ON SCHEMA _realtime TO supabase_admin;

-- ─── JWT settings ─────────────────────────────────────────────────────────────
ALTER DATABASE postgres SET "app.settings.jwt_secret" TO '${JWT_SECRET}';
ALTER DATABASE postgres SET "app.settings.jwt_exp" TO '3600';
